AWSTemplateFormatVersion: 2010-09-09
Description: This template deploys a Cassandra Reaper stack into an existing VPC.

Parameters:
  networkStackName:
    Description: The name of an existing network stack in which Cassandra Reaper will be created.
    Type: String
    MinLength: 1

  keyName:
    Description: The Key Manager key to be added to the list of allowed keys.
    Type: AWS::EC2::KeyPair::KeyName

  instanceType:
    Description: The instance type used for the Cassandra Reaper node.
    Type: String
    MinLength: 1
    Default: t2.small

  authorizedKeys:
    Description: A URL pointing to a list of authorized SSH keys to be appended as-is to ~/.ssh/authorized_keys.
    Type: String
    MinLength: 1

  influxHost:
    Type: String
    Default: ""

  influxPort:
    Type: Number
    Default: 8086

  influxDatabase:
    Type: String
    Default: ""

  influxTagStage:
    Type: String
    Default: ""

  influxTagProduct:
    Type: String
    Default: ""

  influxTagTeam:
    Type: String
    Default: ""

Mappings:
  Regions:
    eu-central-1:
      AmazonLinux2Ami: ami-0f3a43fbf2d3899f7
    eu-west-1:
      AmazonLinux2Ami: ami-01f14919ba412de34

  Scripts:
    Telegraf:
      AddInstanceIdToTelegrafConf: |
        #!/bin/bash -xe
        export INSTANCE_ID=$(curl http://169.254.169.254/latest/meta-data/instance-id)
        sed -i "/  instance =/c\  instance = \"${INSTANCE_ID}\"" /etc/telegraf/telegraf.conf

  Files:
    Telegraf:
      InfluxDbRepo: |
        [influxdb]
        name = InfluxDB Repository - RHEL
        baseurl = https://repos.influxdata.com/rhel/7/x86_64/stable/
        enabled = 1
        gpgcheck = 1
        gpgkey = https://repos.influxdata.com/influxdb.key

      TelegrafConf: |
        [global_tags]
          stage = "{{influxTagStage}}"
          product = "{{influxTagProduct}}"
          region = "${AWS::Region}"
          team = "{{influxTagTeam}}"
          instance =
        [agent]
          interval = "10s"
          round_interval = true
          metric_batch_size = 1000
          metric_buffer_limit = 10000
          collection_jitter = "0s"
          flush_interval = "10s"
          flush_jitter = "0s"
          precision = ""
          debug = false
          quiet = false
          logfile = ""
          hostname = ""
          omit_hostname = false
        [[outputs.influxdb]]
          urls = ["http://{{influxHost}}:{{influxPort}}"]
          database = "{{influxDatabase}}"
        [[inputs.cpu]]
          percpu = true
          totalcpu = true
          collect_cpu_time = false
          report_active = false
        [[inputs.disk]]
          ignore_fs = ["tmpfs", "devtmpfs", "devfs", "overlay", "aufs", "squashfs"]

Resources:
  securityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${AWS::StackName} Reaper Security Group
      GroupDescription: !Sub ${AWS::StackName} Reaper Security Group
      VpcId:
        Fn::ImportValue:
          !Sub "${networkStackName}-vpc"
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName} Reaper Security Group

  bastion22Ingress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref securityGroup
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      SourceSecurityGroupId:
        Fn::ImportValue:
          !Sub "${networkStackName}-bastion-security-group"

  bastion8080Ingress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref securityGroup
      IpProtocol: tcp
      FromPort: 8080
      ToPort: 8080
      SourceSecurityGroupId:
        Fn::ImportValue:
          !Sub "${networkStackName}-bastion-security-group"

  instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap
        - Regions
        - !Ref AWS::Region
        - AmazonLinux2Ami
      KeyName: !Ref keyName
      InstanceType: !Ref instanceType
      SecurityGroupIds:
        - !Ref securityGroup
      SubnetId: !Select
        - 0
        - Fn::Split:
            - ","
            - Fn::ImportValue:
                !Sub "${networkStackName}-private-subnets"
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName} Reaper
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -x
          echo "${project.version} - ${timestamp}"
          yum update -y
          if [ -n "${influxHost}" ]
          then
              CONFIG_SET=setup_with_telegraf
          else
              CONFIG_SET=setup_without_telegraf
          fi
          /opt/aws/bin/cfn-init -v --configsets $CONFIG_SET --stack ${AWS::StackName} --resource instance --region ${AWS::Region}
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource instance --region ${AWS::Region}
    CreationPolicy:
      ResourceSignal:
        Timeout: PT5M
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          setup_with_telegraf:
            - "ssh_keys"
            - "ntp"
            - "haveged"
            - "openjdk8"
            - "add_influxdb_repo"
            - "install_telegraf"
            - "configure_telegraf"
            - "start_telegraf"
            - "add_reaper_repo"
            - "install_reaper"
            - "configure_reaper"
            - "start_reaper"
          setup_without_telegraf:
            - "ssh_keys"
            - "ntp"
            - "haveged"
            - "openjdk8"
            - "add_reaper_repo"
            - "install_reaper"
            - "configure_reaper"
            - "start_reaper"
        ssh_keys:
          files:
            /home/ec2-user/.ssh/additional_keys:
              source: !Ref authorizedKeys
              owner: root
              group: root
              mode: "000644"
          commands:
            register_additional_keys:
              command: "cat /home/ec2-user/.ssh/additional_keys >> /home/ec2-user/.ssh/authorized_keys"
        ntp:
          packages:
            yum:
              ntp: []
          services:
            sysvinit:
              ntpd:
                enabled: true
                ensureRunning: true
                packages:
                  yum:
                    - ntp
        haveged:
          packages:
            rpm:
              haveged: "https://dl.fedoraproject.org/pub/archive/epel/7/x86_64/Packages/h/haveged-1.9.1-1.el7.x86_64.rpm"
          services:
            sysvinit:
              haveged:
                enabled: true
                ensureRunning: true
        openjdk8:
          packages:
            yum:
              java-1.8.0-openjdk: ["1.8.0.222.b10-0.amzn2.0.1"]
              java-1.8.0-openjdk-devel: ["1.8.0.222.b10-0.amzn2.0.1"]
        add_influxdb_repo:
          files:
            /etc/yum.repos.d/influxdb.repo:
              content: !FindInMap ["Files", "Telegraf", "InfluxDbRepo"]
              owner: root
              group: root
              mode: "000644"
        install_telegraf:
          packages:
            yum:
              telegraf: []
        configure_telegraf:
          files:
            /etc/telegraf/telegraf.conf:
              content: !FindInMap ["Files", "Telegraf", "TelegrafConf"]
              context:
                influxHost: !Ref influxHost
                influxPort: !Ref influxPort
                influxDatabase: !Ref influxDatabase
                influxTagStage: !Ref influxTagStage
                influxTagProduct: !Ref influxTagProduct
                influxTagTeam: !Ref influxTagTeam
              owner: ec2-user
              group: ec2-user
              mode: "000644"
          commands:
            add_instance_id_to_telegraf_conf:
              command: !FindInMap ["Scripts", "Telegraf", "AddInstanceIdToTelegrafConf"]
        start_telegraf:
          services:
            sysvinit:
              telegraf:
                enabled: true
                ensureRunning: true
        add_reaper_repo:
          files:
            /etc/yum.repos.d/bintray-thelastpickle-reaper-rpm.repo:
              content: |
                [bintraybintray-thelastpickle-reaper-rpm]
                name=bintray-thelastpickle-reaper-rpm
                baseurl=https://dl.bintray.com/thelastpickle/reaper-rpm
                gpgcheck=0
                repo_gpgcheck=0
                enabled=1
              owner: root
              group: root
              mode: "000644"
        install_reaper:
          packages:
            yum:
              reaper: [1.4.8]
        configure_reaper:
          commands:
            configure_reaper:
              command: |
                #!/bin/bash -xe
                sed -i "/127.0.0.1/c\127.0.0.1 localhost $(curl http://169.254.169.254/latest/meta-data/local-hostname)" /etc/hosts
                export REAPER_YAML=/etc/cassandra-reaper/cassandra-reaper.yaml
                rm ${REAPER_YAML}
                cp /etc/cassandra-reaper/configs/cassandra-reaper-h2.yaml ${REAPER_YAML}
                mkdir /etc/cassandra-reaper/data
                chown reaper /etc/cassandra-reaper/data
                sed -i "/url: jdbc/c\  url: jdbc:h2:\/etc\/cassandra-reaper\/data\/db;MODE=PostgreSQL" ${REAPER_YAML}
                sed -i "/hangingRepairTimeoutMins: 30/c\hangingRepairTimeoutMins: 120" ${REAPER_YAML}
        start_reaper:
          services:
            sysvinit:
              cassandra-reaper:
                enabled: true
                ensureRunning: true

Outputs:
  securityGroup:
    Description: The cassandra reaper security group, so that cassandra security groups can allow ingress from it.
    Value: !Ref securityGroup
    Export:
      Name: !Sub ${AWS::StackName}-security-group
