AWSTemplateFormatVersion: 2010-09-09
Description: This template deploys a VPC with an attached internet gateway.

Parameters:
  cidrBlock:
    Description: The primary CIDR range of the VPC. Note that the maximum size of a CIDR range is 16 bits.
    Type: String
    Default: 10.0.0.0/16

Resources:
  vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref cidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName} VPC

  internetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName} Internet Gateway

  vpcGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref internetGateway
      VpcId: !Ref vpc

Outputs:
  vpc:
    Description: A reference to the created VPC.
    Value: !Ref vpc
    Export:
      Name: !Sub ${AWS::StackName}-vpc

  internetGateway:
    Description: The internet gateway of the created VPC.
    Value: !Ref internetGateway
    Export:
      Name: !Sub ${AWS::StackName}-internet-gateway